new commit
zero-to-mastery/webblocks-2022 pull request #100
Opened 2022-10-04 08:03 UTC by rajmishra-47

# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
This is a new commit made by me to a new project that  I did for the hacktoberfest 22

## Breaking changes
None

## Screenshots
None

2022-10-04 15:06 UTC, sophiabrandt requested changes

2022-10-04 15:06 UTC, sophiabrandt commented on src/blocks/RajMishra2/index.html
> +    <title>new</title>
Could you add a more descriptive title, please?

2022-10-04 15:10 UTC, rajmishra-47 commented
I have made some changes please review it

2022-10-06 22:06 UTC, MattCSmith approved these changes
Looks good to me, nice job 👍

2022-10-06 22:06 UTC, merged