Employee database
zero-to-mastery/webblocks-2022 pull request #124
Opened 2022-10-05 11:09 UTC by MarkL50

# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
- It is an employee database management website created using html CSS and JavaScript where you can create, search ,edit and delete the details of an employee.

## Breaking changes
- None

## Screenshots
-
![Screenshot (18)](https://user-images.githubusercontent.com/76861726/194046962-90a7ce62-8dc0-48e2-96f6-ebcbe0f9163b.png)
![Screenshot (19)](https://user-images.githubusercontent.com/76861726/194046967-4cbec103-0929-4183-88e1-658fad6aaf8c.png)
![Screenshot (20)](https://user-images.githubusercontent.com/76861726/194046971-b42173b9-2f6a-42b0-a72b-d83210c97bff.png)
![Screenshot (21)](https://user-images.githubusercontent.com/76861726/194046977-699bac32-7a5d-4ddf-894d-600651ed4d6c.png)
![Screenshot (22)](https://user-images.githubusercontent.com/76861726/194046980-c375af7c-26a1-42bc-9579-8b288e0ffac0.png)
![Screenshot (23)](https://user-images.githubusercontent.com/76861726/194046981-d1dc7a30-6d60-4216-a67c-6ed99d784d13.png)

2022-10-06 23:43 UTC, MattCSmith requested changes
Looking good but you meta.json is missing a quotation. Please fix so we can merge the PR

2022-10-06 23:43 UTC, MattCSmith commented on src/blocks/MarkL50/meta.json
> +    "author_name": "MarkL50
Missing the closing quotation

2022-10-07 00:46 UTC, MarkL50 commented
@MattCSmith Thanks for pointing this out, I have fixed it now.

2022-10-07 00:50 UTC, MattCSmith approved these changes

2022-10-07 00:51 UTC, merged