Digital Clock
zero-to-mastery/webblocks-2022 pull request #125
Opened 2022-10-05 14:23 UTC by sahilrawat001

# Zero To Mastery - Webblocks 2022 📦📦
 Digital Clock made up of html css and vanila javascript .

2022-10-06 23:49 UTC, MattCSmith requested changes
Looking good so far, however the block.js file should not be edited directly, instead a meta.json file should be created with the relevant information. Please checkout the readme for more information.

2022-10-06 23:49 UTC, MattCSmith commented on src/blocks.js
> +  {
The block.js file should not be edited directly. Please remove and create a meta.json file (see the readme for more information)

2022-10-07 05:54 UTC, sahilrawat001 commented
Now I've added meta.json

2022-10-08 15:06 UTC, sahilrawat001 commented on src/blocks/SahilRawat/meta.json
> +{
updated meta.json as per your requirement

2022-10-08 15:21 UTC, auxfuse approved these changes
LGTM 🤜 👓

2022-10-08 15:21 UTC, merged