add my block to the project - responsive header
zero-to-mastery/webblocks-2022 pull request #192
Opened 2022-10-11 08:04 UTC by K-Wiczling

# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
adding my block to the project

## Breaking changes
None

## Screenshots
None

2022-10-13 19:36 UTC, sophiabrandt requested changes

2022-10-13 19:36 UTC, sophiabrandt commented on src/blocks/kwiczling2/index.html
> +    <title>Resopnisve Header</title>
Typo in "responsive", please fix.

2022-10-13 19:36 UTC, sophiabrandt commented on src/blocks/kwiczling2/style.css
> +    /* padding-top: 25px; */
Please remove outcommented code.

2022-10-15 13:39 UTC, auxfuse approved these changes
Thanks for making those changes sugessted by my colleague @sophiabrandt Everything looks good now 🤜

2022-10-15 13:42 UTC, merged