added a Tennis game
zero-to-mastery/webblocks-2022 pull request #204
Opened 2022-10-12 12:21 UTC by thanmaisai

# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
- Added a Tennis game which is created using html css and javascript.

## Breaking changes
- None

## Screenshots
<img width="805" alt="Screenshot 2022-10-12 at 5 50 25 PM" src="https://user-images.githubusercontent.com/91474486/195341138-40e82dcb-ade1-4eef-905e-0a58737c72bd.png">
<img width="805" alt="Screenshot 2022-10-12 at 5 50 18 PM" src="https://user-images.githubusercontent.com/91474486/195341153-3e9d6ac4-18f1-48eb-9ab0-92ccb62a6f36.png">

2022-10-14 02:28 UTC, MattCSmith requested changes
Hey, 
Looks good so far but there are a couple of things required here:
- Your work should be in the block directory
- You need a meta.json file
- You need an image file

Check the README.md file fore more information.

2022-10-14 05:53 UTC, sophiabrandt requested changes
Screenshot and `meta.json` missing. Please go to the guide in the `README` and follow all steps to create a valid contribution.

2022-10-14 05:53 UTC, sophiabrandt commented on Tennis/index.html
> +        // function coloRect(leftX,topY,width,height,drawColor){
Please remove outdated code.

2022-10-14 05:53 UTC, sophiabrandt commented on Tennis/index.html
> +<!DOCTYPE html>
This file is in the wrong location. Please make a folder with your username in `src/blocks` and move it there.

2022-10-26 12:22 UTC, MattCSmith requested changes
This file and directory still need removing/moving:



![image](https://user-images.githubusercontent.com/6190356/198024758-d89b7438-524b-4c99-a8e4-3f5ae5c58073.png)

Otherwise, it looks good to me!

2022-10-30 11:26 UTC, MattCSmith commented
Closing this PR due to unresolved change request. Feel free to resolve and reopen

2022-10-30 11:26 UTC, closed without merging