Added a Spotify clone
zero-to-mastery/webblocks-2022 pull request #229
Opened 2022-10-15 01:00 UTC by Anjali-ui28

# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
I have made a Spotify clone which has a similar UI as of Spotify web  . It also contains songs which can be played by the user .It contains play/pause, forward/backward buttons to make it more useful.

## Breaking changes
None

## Screenshots
![Screenshot 2022-10-15 060930](https://user-images.githubusercontent.com/83582912/195961948-b7e68de5-5c7f-48f7-89c5-010f618bc4a6.jpg)

2022-10-16 08:10 UTC, sophiabrandt requested changes
Please read the guide on how to contribute to this repository.

Please check if you followed it correctly.

From a first glance, you need to implement the following changes:
a) the contribution is in an incorrect folder
b) `meta.json` with values is missing
c) you use artwork and music files that are licensed or you didn't provide proof that you own the rights or that these works can be used under a permissible license.

2022-10-16 08:10 UTC, sophiabrandt commented on SpotifyClone/script.js
> +console.log("Welcome to Spotify");
Please remove `console.log` from code that you ship to production.

2022-10-16 08:10 UTC, sophiabrandt commented on SpotifyClone/script.js
> +//audioElement.play();
Please remove outdated code.

2022-10-26 12:27 UTC, MattCSmith commented
Closing due to unresolved change request. Feel free to resolve and reopen.

2022-10-26 12:27 UTC, closed without merging