adding blog site
zero-to-mastery/webblocks-2022 pull request #279
Opened 2022-10-17 18:46 UTC by noobmaster432

2022-10-18 04:47 UTC, sophiabrandt requested changes
1. Please provide the licenses to the images and icons you used, so that we can be sure that we don't violate copyright.

2. Please fill out the request template instead of deleting it.

2022-10-18 04:47 UTC, sophiabrandt commented on src/blocks.js
> +  },
Please see the guide and revert your changes to this file:

> Please keep src/blocks.js as it is. If you follow step 10 above, a script will add your art automatically after your PR is merged.

2022-10-18 04:47 UTC, sophiabrandt commented on src/blocks/noobmaster432/css/style.css
> +  /* height: 74px;  */
Please remove outdated code

2022-10-18 04:47 UTC, sophiabrandt commented on src/blocks/noobmaster432/css/style.css
> +/* .home-articles{} */
Same here.

2022-10-26 12:41 UTC, MattCSmith commented
Closing due to unresolved change request. Feel free to resolve and reopen.

2022-10-26 12:41 UTC, closed without merging