adding my webblocks to the project
zero-to-mastery/webblocks-2022 pull request #306
Opened 2022-10-19 22:53 UTC by dhiraj1008

please add to the list @royranger

2022-10-20 06:18 UTC, sophiabrandt commented
Please remove git submodule.

Please provide license to the images you used to make sure that we don't violate copyright by merging your PR.

2022-10-20 06:19 UTC, sophiabrandt commented on src/blocks/after/index.html
> +    <body background="bg.jpg">
You need to commit the images to git, too, or this won't work. Or link to a public URL.

2022-10-20 06:20 UTC, sophiabrandt requested changes

2022-10-20 06:20 UTC, sophiabrandt commented on src/blocks/after/style.css
> +
Nitpick: please remove all the empty lines.

2022-10-26 12:55 UTC, MattCSmith commented
Closing due to unresolved change request. Feel free to resolve and reopen.

2022-10-26 12:55 UTC, closed without merging