Hacktober
zero-to-mastery/webblocks-2022 pull request #336
Opened 2022-10-25 08:11 UTC by Saga-sanga

# Zero To Mastery - Webblocks 2022 📦📦

## PR contains:
- Fix to thank you card overlaying incorrectly over the rating card in mobile view.

## Breaking changes
- None

## Screenshots
- None

2022-10-25 12:25 UTC, sophiabrandt requested changes

2022-10-25 12:25 UTC, sophiabrandt commented on src/blocks/saga-sanga/index.css
> +  /* justify-self: center; */
Same in line 200 & 201.

2022-10-25 15:32 UTC, Saga-sanga commented on src/blocks/saga-sanga/index.css
>    /* padding-block: 2rem; */
All right. Will do.

2022-10-25 15:33 UTC, Saga-sanga commented
@sophiabrandt I have made the requested changes.

2022-10-26 13:53 UTC, MattCSmith approved these changes
Looks good to me 👍

2022-10-26 13:53 UTC, merged