Added Analog Clock project using HTML, CSS, and JavaScript
zero-to-mastery/webblocks-2022 pull request #341
Opened 2022-10-25 21:03 UTC by ShubhanshuJha

# Zero To Mastery - Webblocks 2022 📦📦

 ## PR contains:
- INFO ABOUT YOUR PULL REQUEST GOES HERE (Please be as descriptive as possible) 🤜

## Checklist
 Put an `x` in all the boxes that apply: <br>
 

- [] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.

 ## What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| icon.png  | Title goes here   |
| Image goes here  | Image goes here   |

2022-10-25 21:03 UTC, ShubhanshuJha commented
Added a new project, and did every step as per the suggestion.

2022-10-26 11:17 UTC, sophiabrandt requested changes
Please provide the license to the audio file you used, see [here](https://github.com/zero-to-mastery/webblocks-2022#%EF%B8%8F-rules):
> If you use images or audio files, please make sure that you are allowed to use these (don't violate copyright!) - please add a link to the license into the pull request template

2022-10-26 11:17 UTC, sophiabrandt commented on src/blocks/ShubhanshuJha/style.css
> +    /* opacity: 0.6; */
Please remove all outdate code (everything that's commented out) in this file.

2022-10-26 11:51 UTC, ShubhanshuJha commented
Did the change as per the suggestion.

2022-10-28 08:12 UTC, sophiabrandt commented
@ShubhanshuJha please provide answer to my comment above, otherwise we cannot merge your request, as we don't want to violate copyright.

2022-10-28 08:56 UTC, ShubhanshuJha commented
Yes, I added the license to use the image file.
And, removed the music, as I didn't have the license to use it anywhere.

2022-10-30 13:42 UTC, merged