Magic 8 Ball Hacktoberfest 2022
zero-to-mastery/webblocks-2022 pull request #355
Opened 2022-10-27 01:45 UTC by irvrivera

# Zero To Mastery - Webblocks 2022 📦📦

 ## PR contains:
- Added magic 8 ball. Hacktoberfest 2022
## Screenshots
![](https://raw.githubusercontent.com/zero-to-mastery/webblocks-2022/904a167106ab6130915572b48a204c165b077ff7/src/blocks/irvrivera/icon.png)

## Checklist
 Put an `x` in all the boxes that apply: <br>
 

- [ ] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.

 ## What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-10-27 15:14 UTC, sophiabrandt requested changes

2022-10-27 15:14 UTC, sophiabrandt commented on src/blocks.js
> +  {
Please roll back any changes to this file, see the README, point 10.

2022-10-30 12:32 UTC, MattCSmith commented
Closing this PR due to the unresolved change request. 
Please remove the changes to the blocks.js file and reopen

2022-10-30 12:32 UTC, closed without merging

2022-10-30 18:27 UTC, irvrivera commented
sorry I am very very new at this. I thought the pull request was accepted. and had no idea to come back and look. sorry again.